# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f6a296734ad47ceb1301130ed4e5de79d374bc4e5e1339ce61f5274cc6bc39940bc976c57fe301d18fc4b980111eadfe56330add06ac318db67ecf6b72333cd

test:
  secret_key_base: eb5c7771017bf8ade2a1bae53ae66a20bf8ec0aedbd1c55982daf79d6a95cf365ee11dfaf7b09e36595128ed1364c5982d47a811b524e86e765aaa86310dcad2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
